"""
#  exploring Apple-default .mlmodels until I got distracted

```
/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PhoneAppPredictorPeopleCentric.mlmodelc
/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/AutoG2P8B.mlmodelc
/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/FstSpotterConfig/m8_ANE_newdata_quantized.mlmodelc
/System/Library/PrivateFrameworks/TextUnderstandingShared.framework/Versions/A/Resources/en.lproj/TextUnderstandingSupport.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/LOITypeToOneHotTransformer.mlmodelc
```


```
sudo find / 2>/dev/null | grep '\.mlmodelc$' > ~/mlmodelc_files.txt

```



"""


import os #, pathlib #, coremltools
import sys

while(mlmodel_filename := sys.stdin.readline().rstrip()):
    if '/System/Volumes/' in mlmodel_filename:
        continue


    #print (f"{'Y' if os.path.exists(mlmodel_filename) else 'N'} {mlmodel_filename}")
    #if os.path.exists(mlmodel_filename):
    #    print("File %s exists" % mlmodel_filename)
    # mlmodel = mlmodel.strip()
    # print("Loading %s" % mlmodel)
    # coreml_model = coremltools.models.MLModel(mlmodel)
    # print("Loaded %s" % mlmodel)


    # /System/Volumes/Update/mnt1/
    #if '/System/Volumes/' in mlmodel_filename:


        # model_name
        # model_path
        # model_owner


"""
/usr/libexec/engageOnPlugin.mlmodelc
/usr/libexec/_OSHighBatteryDrainHighChargeDurationModel.mlmodelc
/usr/libexec/WiFiStallDetect.mlmodelc
/usr/libexec/_OSHighBatteryDrainLowChargeDurationModel.mlmodelc
/usr/libexec/longDurationModel.mlmodelc
/usr/libexec/shortDurationModel.mlmodelc
/usr/sbin/iRATBW.mlmodelc
/System/iOSSupport/System/Library/PrivateFrameworks/IMTranscoderAgent.framework/Versions/A/Resources/Image_Estimator_HEIF.mlmodelc
/System/Library/CoreServices/MapsSuggestionsTransportModePrediction.mlmodelc
/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_1_NN_V5_Model_DeviceType_201.mlmodelc
/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_2_NN_V5_Model_DeviceType_201.mlmodelc
/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_1_NN_V5_ScalingModel_DeviceType_201.mlmodelc
/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_2_NN_V5_ScalingModel_DeviceType_201.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/4eea56458f200ed6da91e6e5bb9a4da157a76954.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/604acb022f2441e8fe0bec11b0f0d03c01a1f334.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/a9b8a73d04748207e58bcf4f902752c7c8e6ad5d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/826be8983150028b8c03ef94e3a3ad83bdfecf60.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/5bdcdd33041f9c430aef147e2859213841b31133.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/d5bebef0cd7d5e59b9ffd61c9e28e3a2a23ccf44.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/38cffe926590d0761b9870d9321d36e08cc4fb2d.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/55983fc0e829e6d0d95be9344d59405ac48a16f7.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/3db58ff2911500a0f30880af860f4416c9bf9cfe.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/c195170f7d486477cfd8a6d45b71568bc5d32754.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/26c7e677f61ce8a6f0c28f7e70cc49ed5a92e35d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/33f16d017d237a3320bc7de5e30f25744c869b3a.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/50e24ea01cac360631cb1942f94b32ac81f17124.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/ea4658aa486ce4fba650860f28f5a9cfb0cb4569.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/bd930ec2b441b82993acbf87557ee7eeaf09454d.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/08677b305618a798d458858a7ba6d4700c94793d.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/1649e8abe0d875e1c3db8e53b80e7c16e11567be.asset/AssetData/ssu_encoder/nessie.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/89b344ad16399a8574331077206c5250fa712bce.asset/AssetData/model_bundle_psc/PSC/PSC.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/3b3bb2ab11657146b3f88fb97dcdae73e70585ce.asset/AssetData/siri_input_representations/bert.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/f6c6c3caa9ffa8123706f7d3eef040a3d08d32fa.asset/AssetData/temp_model/model_bundle/v3/encoder.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/f6c6c3caa9ffa8123706f7d3eef040a3d08d32fa.asset/AssetData/temp_model/model_bundle/v3/decoder.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/5d25d24c158f460b820734ca3e030698e95d28f9.asset/AssetData/model_bundle_snlc/SNLC/SNLC.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/40339fdb04bf604e108f7e870aad3d597814c01d.asset/AssetData/marrs/ccqr/joint_ccqr.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/aa3963b3dfde1312aa5bc9b0278cba488256162c.asset/AssetData/marrs/mr/visual/modelBased/converted_model.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/181bfcce7cf8072bfec0f600db5ae0d244789328.asset/AssetData/marrs/md/classifier_model.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/4eea56458f200ed6da91e6e5bb9a4da157a76954.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/604acb022f2441e8fe0bec11b0f0d03c01a1f334.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/a9b8a73d04748207e58bcf4f902752c7c8e6ad5d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/826be8983150028b8c03ef94e3a3ad83bdfecf60.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/5bdcdd33041f9c430aef147e2859213841b31133.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/d5bebef0cd7d5e59b9ffd61c9e28e3a2a23ccf44.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/38cffe926590d0761b9870d9321d36e08cc4fb2d.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/55983fc0e829e6d0d95be9344d59405ac48a16f7.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/3db58ff2911500a0f30880af860f4416c9bf9cfe.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/c195170f7d486477cfd8a6d45b71568bc5d32754.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/26c7e677f61ce8a6f0c28f7e70cc49ed5a92e35d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/33f16d017d237a3320bc7de5e30f25744c869b3a.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/50e24ea01cac360631cb1942f94b32ac81f17124.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/ea4658aa486ce4fba650860f28f5a9cfb0cb4569.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/bd930ec2b441b82993acbf87557ee7eeaf09454d.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/08677b305618a798d458858a7ba6d4700c94793d.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAsrAssistant/purpose_auto/9209cffd1c8fe2e94e8b0fcee8d0d48f83b304cb.asset/AssetData/OEP/EEPmodel_v8_hallucination_1.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAsrAssistant/purpose_auto/9209cffd1c8fe2e94e8b0fcee8d0d48f83b304cb.asset/AssetData/OEP/EEPmodel_Dictation_v1_hallucination_1.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAsrAssistant/purpose_auto/9209cffd1c8fe2e94e8b0fcee8d0d48f83b304cb.asset/AssetData/TP/tantor/hybrid_coreml/punc/punc_model.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_CoreSuggestions/955b7ebcb6693fea61a8e0404c834be4ccbf0ff3.asset/AssetData/ReminderModel.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_CoreSuggestions/955b7ebcb6693fea61a8e0404c834be4ccbf0ff3.asset/AssetData/structuredEventGazetteer.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_CoreSuggestions/955b7ebcb6693fea61a8e0404c834be4ccbf0ff3.asset/AssetData/StructuredEventModel.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/89838a22d3ba7ec25ec760f96aa9463bdd08e0b3.asset/AssetData/nlda/best_model.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/89838a22d3ba7ec25ec760f96aa9463bdd08e0b3.asset/AssetData/aftm/keyword_aftm/tcn_aftm_o13.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/89838a22d3ba7ec25ec760f96aa9463bdd08e0b3.asset/AssetData/sdsd/mega_model_v7.0_renamed.mlmodelc
/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/fa45b81a214906b04384eb178d073fb1e3842a8f.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PervasiveEntityResolution.mlmodelc
/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PhoneAppPredictor.mlmodelc
/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/ContactRanker.mlmodelc
/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/ContactRanker_watchos_ios_baxter.mlmodelc
/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PhoneAppPredictorPeopleCentric.mlmodelc
/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/AutoG2P8B.mlmodelc
/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/FstSpotterConfig/m8_ANE_newdata_quantized.mlmodelc
/System/Library/PrivateFrameworks/TextUnderstandingShared.framework/Versions/A/Resources/en.lproj/TextUnderstandingSupport.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/LOITypeToOneHotTransformer.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityTagging_FamilyAndFriends.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/locationEncoder.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityTagging_Family.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/DiningOutModel.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/ETShadowModel.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityRelevanceModel.mlmodelc
/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_102/PPModel_NE_Filtering.mlmodelc
/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_108/social_highlights_scorer.mlmodelc
/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_108/social_highlights_top_k_scorer.mlmodelc
/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_100/context_predictor.mlmodelc
/System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/Versions/A/Resources/assets_130/model/model.mlmodelc
/System/Library/PrivateFrameworks/SpotlightServices.framework/Versions/A/Resources/L2XGBRegressor.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_gbdt.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_dt.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/ContactRankerModel.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/interactionPrediction.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/sharesheetEmptyBaseModel.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_rf.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_IP_gbdt.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/RuleImportancePredictor.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/compiledShareSheetModel.mlmodelc
/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/cloud_mlp_with_embedding.mlmodelc
/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/vmrefiner.mlmodelc
/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/visegHQ_memory.mlmodelc
/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/visegHQ_mask_memory_shared.mlmodelc
/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/anst.mlmodelc
/System/Library/PrivateFrameworks/IMTranscoderAgent.framework/Versions/A/Resources/Image_Estimator_HEIF.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MentionGenerationModel.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/EntityRerankerModel.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MDNameToNamePersonLinker.mlmodelc
/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MDNameToEmailPersonLinker.mlmodelc
/System/Library/PrivateFrameworks/NewsCore.framework/Versions/A/Resources/FCUserVectorModel.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_fr-FR.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_zh-Hans.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_it-IT.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_pt-BR.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_de-DE.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_uk-UA.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_vi-VT.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_en-US.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ru-RU.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ja-JP.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ko-KR.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_es-ES.mlmodelc
/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_th-TH.mlmodelc
/System/Library/PrivateFrameworks/WiFiAnalytics.framework/WiFiStallDetect.mlmodelc
/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.uncertainty_prompt/UncertaintyPrompt.mlmodelc
/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.auto_confirm.auto_send/AutoSendModel.mlmodelc
/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.auto_confirm.auto_send_private/AutoSendPrivateNoOp.mlmodelc
/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.caar.ranker/Ranker.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_ultra.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_series.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/easy_engage.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/base_duration.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_model_iphone.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_model.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/mac_routine_reg.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/long_duration.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/mac_routine_eng.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/base_engage.mlmodelc
/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/shallow_model.mlmodelc
/System/Library/PrivateFrameworks/PromotedContentPrediction.framework/Versions/A/Resources/assets_513/PTTRMLModel/gibraltar_identity_d8f9a11.mlmodelc
/System/Library/PrivateFrameworks/PromotedContentPrediction.framework/Versions/A/Resources/assets_514/PTTRMLModel/gibraltar_identity_d8f9a11.mlmodelc
/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2.mlmodelc
/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2_recency_mail.mlmodelc
/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2_mail.mlmodelc
/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/333/suggestions_blending.mlmodelc
/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/action_repetition_counter.mlmodelc
/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/MonzaV4_1.mlmodelc
/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/hand_gesture_dynamic_two_hand_5fps.mlmodelc
/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/hand_gesture_static.mlmodelc
/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTPlaceTypeClassifierModelMultiClass.mlmodelc
/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTVisitTrajectorySequenceClassifierBatchMode.mlmodelc
/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTPlaceTypeClassifierModelRanker.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/3DHumanPoseLiftingSequenceFirstStage.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H13/2DHumanPoseDetectorFull_H13.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H13/3DHumanPoseLiftingSequenceFirstStage_H13.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H14/2DHumanPoseDetectorFull_H14.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H14/3DHumanPoseLiftingSequenceFirstStage_H14.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H15/2DHumanPoseDetectorFull_H15.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H15/3DHumanPoseLiftingSequenceFirstStage_H15.mlmodelc
/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/2DHumanPoseDetectorFull.mlmodelc
/System/Library/PrivateFrameworks/TranslationDaemon.framework/Versions/A/Resources/LanguageDetectorDefaultAsset/confLID.mlmodelc
/System/Library/PrivateFrameworks/TranslationDaemon.framework/Versions/A/Resources/LanguageDetectorDefaultAsset/AcousticLID.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishApplauseModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundClassifierVersion1Model.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kSmokeAlarmModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintASmokeAlarmModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishDistressedBabyModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kFireAlarmModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishFireAlarmModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishCheeringModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishBabbleModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNAudioQualityModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishMusicModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintKEmbeddingModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintAEmbeddingModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishEmbeddingModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishLaughterModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishSpeechModel.mlmodelc
/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kEmbeddingModel.mlmodelc
/System/Volumes/Update/mnt1/usr/libexec/engageOnPlugin.mlmodelc
/System/Volumes/Update/mnt1/usr/libexec/_OSHighBatteryDrainHighChargeDurationModel.mlmodelc
/System/Volumes/Update/mnt1/usr/libexec/WiFiStallDetect.mlmodelc
/System/Volumes/Update/mnt1/usr/libexec/_OSHighBatteryDrainLowChargeDurationModel.mlmodelc
/System/Volumes/Update/mnt1/usr/libexec/longDurationModel.mlmodelc
/System/Volumes/Update/mnt1/usr/libexec/shortDurationModel.mlmodelc
/System/Volumes/Update/mnt1/usr/sbin/iRATBW.mlmodelc
/System/Volumes/Update/mnt1/System/iOSSupport/System/Library/PrivateFrameworks/IMTranscoderAgent.framework/Versions/A/Resources/Image_Estimator_HEIF.mlmodelc
/System/Volumes/Update/mnt1/System/Library/CoreServices/MapsSuggestionsTransportModePrediction.mlmodelc
/System/Volumes/Update/mnt1/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_1_NN_V5_Model_DeviceType_201.mlmodelc
/System/Volumes/Update/mnt1/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_2_NN_V5_Model_DeviceType_201.mlmodelc
/System/Volumes/Update/mnt1/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_1_NN_V5_ScalingModel_DeviceType_201.mlmodelc
/System/Volumes/Update/mnt1/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_2_NN_V5_ScalingModel_DeviceType_201.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/4eea56458f200ed6da91e6e5bb9a4da157a76954.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/604acb022f2441e8fe0bec11b0f0d03c01a1f334.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/a9b8a73d04748207e58bcf4f902752c7c8e6ad5d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/826be8983150028b8c03ef94e3a3ad83bdfecf60.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/5bdcdd33041f9c430aef147e2859213841b31133.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/d5bebef0cd7d5e59b9ffd61c9e28e3a2a23ccf44.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/38cffe926590d0761b9870d9321d36e08cc4fb2d.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/55983fc0e829e6d0d95be9344d59405ac48a16f7.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/3db58ff2911500a0f30880af860f4416c9bf9cfe.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/c195170f7d486477cfd8a6d45b71568bc5d32754.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/26c7e677f61ce8a6f0c28f7e70cc49ed5a92e35d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/33f16d017d237a3320bc7de5e30f25744c869b3a.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/50e24ea01cac360631cb1942f94b32ac81f17124.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/ea4658aa486ce4fba650860f28f5a9cfb0cb4569.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/bd930ec2b441b82993acbf87557ee7eeaf09454d.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/08677b305618a798d458858a7ba6d4700c94793d.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PervasiveEntityResolution.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PhoneAppPredictor.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/ContactRanker.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/ContactRanker_watchos_ios_baxter.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PhoneAppPredictorPeopleCentric.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/AutoG2P8B.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/FstSpotterConfig/m8_ANE_newdata_quantized.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextUnderstandingShared.framework/Versions/A/Resources/en.lproj/TextUnderstandingSupport.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/LOITypeToOneHotTransformer.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityTagging_FamilyAndFriends.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/locationEncoder.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityTagging_Family.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/DiningOutModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/ETShadowModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityRelevanceModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_102/PPModel_NE_Filtering.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_108/social_highlights_scorer.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_108/social_highlights_top_k_scorer.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_100/context_predictor.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/Versions/A/Resources/assets_130/model/model.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SpotlightServices.framework/Versions/A/Resources/L2XGBRegressor.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_gbdt.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_dt.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/ContactRankerModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/interactionPrediction.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/sharesheetEmptyBaseModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_rf.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_IP_gbdt.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/RuleImportancePredictor.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/compiledShareSheetModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/cloud_mlp_with_embedding.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/vmrefiner.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/visegHQ_memory.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/visegHQ_mask_memory_shared.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/anst.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IMTranscoderAgent.framework/Versions/A/Resources/Image_Estimator_HEIF.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MentionGenerationModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/EntityRerankerModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MDNameToNamePersonLinker.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MDNameToEmailPersonLinker.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/NewsCore.framework/Versions/A/Resources/FCUserVectorModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_fr-FR.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_zh-Hans.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_it-IT.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_pt-BR.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_de-DE.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_uk-UA.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_vi-VT.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_en-US.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ru-RU.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ja-JP.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ko-KR.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_es-ES.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_th-TH.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/WiFiAnalytics.framework/WiFiStallDetect.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.uncertainty_prompt/UncertaintyPrompt.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.auto_confirm.auto_send/AutoSendModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.auto_confirm.auto_send_private/AutoSendPrivateNoOp.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.caar.ranker/Ranker.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_ultra.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_series.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/easy_engage.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/base_duration.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_model_iphone.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_model.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/mac_routine_reg.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/long_duration.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/mac_routine_eng.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/base_engage.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/shallow_model.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PromotedContentPrediction.framework/Versions/A/Resources/assets_513/PTTRMLModel/gibraltar_identity_d8f9a11.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/PromotedContentPrediction.framework/Versions/A/Resources/assets_514/PTTRMLModel/gibraltar_identity_d8f9a11.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2_recency_mail.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2_mail.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/333/suggestions_blending.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/action_repetition_counter.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/MonzaV4_1.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/hand_gesture_dynamic_two_hand_5fps.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/hand_gesture_static.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTPlaceTypeClassifierModelMultiClass.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTVisitTrajectorySequenceClassifierBatchMode.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTPlaceTypeClassifierModelRanker.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/3DHumanPoseLiftingSequenceFirstStage.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H13/2DHumanPoseDetectorFull_H13.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H13/3DHumanPoseLiftingSequenceFirstStage_H13.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H14/2DHumanPoseDetectorFull_H14.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H14/3DHumanPoseLiftingSequenceFirstStage_H14.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H15/2DHumanPoseDetectorFull_H15.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H15/3DHumanPoseLiftingSequenceFirstStage_H15.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/2DHumanPoseDetectorFull.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TranslationDaemon.framework/Versions/A/Resources/LanguageDetectorDefaultAsset/confLID.mlmodelc
/System/Volumes/Update/mnt1/System/Library/PrivateFrameworks/TranslationDaemon.framework/Versions/A/Resources/LanguageDetectorDefaultAsset/AcousticLID.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishApplauseModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundClassifierVersion1Model.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kSmokeAlarmModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintASmokeAlarmModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishDistressedBabyModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kFireAlarmModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishFireAlarmModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishCheeringModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishBabbleModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNAudioQualityModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishMusicModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintKEmbeddingModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintAEmbeddingModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishEmbeddingModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishLaughterModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishSpeechModel.mlmodelc
/System/Volumes/Update/mnt1/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kEmbeddingModel.mlmodelc
/System/Volumes/Data/System/iOSSupport/System/Library/PrivateFrameworks/IMTranscoderAgent.framework/Versions/A/Resources/Image_Estimator_HEIF.mlmodelc
/System/Volumes/Data/System/Library/CoreServices/MapsSuggestionsTransportModePrediction.mlmodelc
/System/Volumes/Data/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_1_NN_V5_Model_DeviceType_201.mlmodelc
/System/Volumes/Data/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_2_NN_V5_Model_DeviceType_201.mlmodelc
/System/Volumes/Data/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_1_NN_V5_ScalingModel_DeviceType_201.mlmodelc
/System/Volumes/Data/System/Library/NearbyInteractionBundles/BiasEstimatorResourceBundle.bundle/Contents/Resources/AntennaMask_2_NN_V5_ScalingModel_DeviceType_201.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/4eea56458f200ed6da91e6e5bb9a4da157a76954.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/604acb022f2441e8fe0bec11b0f0d03c01a1f334.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/a9b8a73d04748207e58bcf4f902752c7c8e6ad5d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/826be8983150028b8c03ef94e3a3ad83bdfecf60.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/5bdcdd33041f9c430aef147e2859213841b31133.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/d5bebef0cd7d5e59b9ffd61c9e28e3a2a23ccf44.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/38cffe926590d0761b9870d9321d36e08cc4fb2d.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/55983fc0e829e6d0d95be9344d59405ac48a16f7.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/3db58ff2911500a0f30880af860f4416c9bf9cfe.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/c195170f7d486477cfd8a6d45b71568bc5d32754.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/26c7e677f61ce8a6f0c28f7e70cc49ed5a92e35d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/33f16d017d237a3320bc7de5e30f25744c869b3a.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/50e24ea01cac360631cb1942f94b32ac81f17124.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/ea4658aa486ce4fba650860f28f5a9cfb0cb4569.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/bd930ec2b441b82993acbf87557ee7eeaf09454d.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/Templates/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/08677b305618a798d458858a7ba6d4700c94793d.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/1649e8abe0d875e1c3db8e53b80e7c16e11567be.asset/AssetData/ssu_encoder/nessie.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/89b344ad16399a8574331077206c5250fa712bce.asset/AssetData/model_bundle_psc/PSC/PSC.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/3b3bb2ab11657146b3f88fb97dcdae73e70585ce.asset/AssetData/siri_input_representations/bert.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/f6c6c3caa9ffa8123706f7d3eef040a3d08d32fa.asset/AssetData/temp_model/model_bundle/v3/encoder.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/f6c6c3caa9ffa8123706f7d3eef040a3d08d32fa.asset/AssetData/temp_model/model_bundle/v3/decoder.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/5d25d24c158f460b820734ca3e030698e95d28f9.asset/AssetData/model_bundle_snlc/SNLC/SNLC.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/40339fdb04bf604e108f7e870aad3d597814c01d.asset/AssetData/marrs/ccqr/joint_ccqr.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/aa3963b3dfde1312aa5bc9b0278cba488256162c.asset/AssetData/marrs/mr/visual/modelBased/converted_model.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingNL/purpose_auto/181bfcce7cf8072bfec0f600db5ae0d244789328.asset/AssetData/marrs/md/classifier_model.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/4eea56458f200ed6da91e6e5bb9a4da157a76954.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/604acb022f2441e8fe0bec11b0f0d03c01a1f334.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/a9b8a73d04748207e58bcf4f902752c7c8e6ad5d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/826be8983150028b8c03ef94e3a3ad83bdfecf60.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/5bdcdd33041f9c430aef147e2859213841b31133.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/d5bebef0cd7d5e59b9ffd61c9e28e3a2a23ccf44.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/38cffe926590d0761b9870d9321d36e08cc4fb2d.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsStudioDisplay/55983fc0e829e6d0d95be9344d59405ac48a16f7.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/3db58ff2911500a0f30880af860f4416c9bf9cfe.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/c195170f7d486477cfd8a6d45b71568bc5d32754.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/26c7e677f61ce8a6f0c28f7e70cc49ed5a92e35d.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/33f16d017d237a3320bc7de5e30f25744c869b3a.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/50e24ea01cac360631cb1942f94b32ac81f17124.asset/AssetData/keyword/megatron_mtl_v3_8bit.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/ea4658aa486ce4fba650860f28f5a9cfb0cb4569.asset/AssetData/keyword/megatron_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/bd930ec2b441b82993acbf87557ee7eeaf09454d.asset/AssetData/keyword/megatron_hsjs_8bit_compressed_v1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/PreinstalledAssetsV2/RequiredByOs/com_apple_MobileAsset_VoiceTriggerAssetsASMac/08677b305618a798d458858a7ba6d4700c94793d.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAsrAssistant/purpose_auto/9209cffd1c8fe2e94e8b0fcee8d0d48f83b304cb.asset/AssetData/OEP/EEPmodel_v8_hallucination_1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAsrAssistant/purpose_auto/9209cffd1c8fe2e94e8b0fcee8d0d48f83b304cb.asset/AssetData/OEP/EEPmodel_Dictation_v1_hallucination_1.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAsrAssistant/purpose_auto/9209cffd1c8fe2e94e8b0fcee8d0d48f83b304cb.asset/AssetData/TP/tantor/hybrid_coreml/punc/punc_model.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_CoreSuggestions/955b7ebcb6693fea61a8e0404c834be4ccbf0ff3.asset/AssetData/ReminderModel.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_CoreSuggestions/955b7ebcb6693fea61a8e0404c834be4ccbf0ff3.asset/AssetData/structuredEventGazetteer.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_CoreSuggestions/955b7ebcb6693fea61a8e0404c834be4ccbf0ff3.asset/AssetData/StructuredEventModel.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/89838a22d3ba7ec25ec760f96aa9463bdd08e0b3.asset/AssetData/nlda/best_model.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/89838a22d3ba7ec25ec760f96aa9463bdd08e0b3.asset/AssetData/aftm/keyword_aftm/tcn_aftm_o13.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/89838a22d3ba7ec25ec760f96aa9463bdd08e0b3.asset/AssetData/sdsd/mega_model_v7.0_renamed.mlmodelc
/System/Volumes/Data/System/Library/AssetsV2/com_apple_MobileAsset_Trial_Siri_SiriUnderstandingAttentionAssets/purpose_auto/fa45b81a214906b04384eb178d073fb1e3842a8f.asset/AssetData/keyword/megatron_hsjs_v2_8bit.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PervasiveEntityResolution.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PhoneAppPredictor.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/ContactRanker.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/ContactRanker_watchos_ios_baxter.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriInference.framework/Versions/A/Resources/PhoneAppPredictorPeopleCentric.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/AutoG2P8B.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/VoiceActions.framework/Versions/A/Resources/FstSpotterConfig/m8_ANE_newdata_quantized.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextUnderstandingShared.framework/Versions/A/Resources/en.lproj/TextUnderstandingSupport.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/LOITypeToOneHotTransformer.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityTagging_FamilyAndFriends.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/locationEncoder.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityTagging_Family.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/DiningOutModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/ETShadowModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatformCore.framework/Versions/A/Resources/EntityRelevanceModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_102/PPModel_NE_Filtering.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_108/social_highlights_scorer.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_108/social_highlights_top_k_scorer.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PersonalizationPortraitInternals.framework/Versions/A/Resources/assets_100/context_predictor.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/CoreSuggestionsInternals.framework/Versions/A/Resources/assets_130/model/model.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SpotlightServices.framework/Versions/A/Resources/L2XGBRegressor.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_gbdt.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_dt.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/ContactRankerModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/interactionPrediction.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/sharesheetEmptyBaseModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_rf.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/iCloudFamilyModel_IP_gbdt.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/RuleImportancePredictor.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/compiledShareSheetModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PeopleSuggester.framework/Versions/A/Resources/cloud_mlp_with_embedding.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/vmrefiner.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/visegHQ_memory.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/visegHQ_mask_memory_shared.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/ANSTKit.framework/Versions/A/Resources/Models/anst.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IMTranscoderAgent.framework/Versions/A/Resources/Image_Estimator_HEIF.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MentionGenerationModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/EntityRerankerModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MDNameToNamePersonLinker.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/IntelligencePlatform.framework/Versions/A/Resources/MDNameToEmailPersonLinker.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/NewsCore.framework/Versions/A/Resources/FCUserVectorModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_fr-FR.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_zh-Hans.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_it-IT.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_pt-BR.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_de-DE.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_uk-UA.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_vi-VT.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_en-US.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ru-RU.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ja-JP.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_ko-KR.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_es-ES.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TextRecognition.framework/Versions/A/Resources/cr_lw_th-TH.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/WiFiAnalytics.framework/WiFiStallDetect.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.uncertainty_prompt/UncertaintyPrompt.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.auto_confirm.auto_send/AutoSendModel.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.cam.auto_confirm.auto_send_private/AutoSendPrivateNoOp.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SiriCam.framework/Versions/A/Resources/assets_750/com.apple.siri.caar.ranker/Ranker.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_ultra.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_series.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/easy_engage.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/base_duration.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_model_iphone.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/deoc_model.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/mac_routine_reg.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/long_duration.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/mac_routine_eng.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/base_engage.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PowerUI.framework/Versions/A/Resources/shallow_model.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PromotedContentPrediction.framework/Versions/A/Resources/assets_513/PTTRMLModel/gibraltar_identity_d8f9a11.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/PromotedContentPrediction.framework/Versions/A/Resources/assets_514/PTTRMLModel/gibraltar_identity_d8f9a11.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2_recency_mail.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/spotlightservices/spotlight_l2_mail.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/SpotlightResources.framework/Versions/A/Resources/RequiredAssets_root.bundle/AssetData/333/suggestions_blending.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/action_repetition_counter.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/MonzaV4_1.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/hand_gesture_dynamic_two_hand_5fps.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/MediaAnalysis.framework/Versions/A/Resources/hand_gesture_static.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTPlaceTypeClassifierModelMultiClass.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTVisitTrajectorySequenceClassifierBatchMode.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/CoreRoutine.framework/Versions/A/Resources/RTPlaceTypeClassifierModelRanker.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/3DHumanPoseLiftingSequenceFirstStage.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H13/2DHumanPoseDetectorFull_H13.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H13/3DHumanPoseLiftingSequenceFirstStage_H13.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H14/2DHumanPoseDetectorFull_H14.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H14/3DHumanPoseLiftingSequenceFirstStage_H14.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H15/2DHumanPoseDetectorFull_H15.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/H15/3DHumanPoseLiftingSequenceFirstStage_H15.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/AltruisticBodyPoseKit.framework/2DHumanPoseDetectorFull.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TranslationDaemon.framework/Versions/A/Resources/LanguageDetectorDefaultAsset/confLID.mlmodelc
/System/Volumes/Data/System/Library/PrivateFrameworks/TranslationDaemon.framework/Versions/A/Resources/LanguageDetectorDefaultAsset/AcousticLID.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishApplauseModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundClassifierVersion1Model.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kSmokeAlarmModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintASmokeAlarmModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishDistressedBabyModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kFireAlarmModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishFireAlarmModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishCheeringModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishBabbleModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNAudioQualityModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishMusicModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintKEmbeddingModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrintAEmbeddingModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishEmbeddingModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishLaughterModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNVGGishSpeechModel.mlmodelc
/System/Volumes/Data/System/Library/Frameworks/SoundAnalysis.framework/Versions/A/Resources/SNSoundPrint100kEmbeddingModel.mlmodelc
/System/Volumes/Data/private/var/db/PowerUI/mac_routine_reg.mlmodelc
/System/Volumes/Data/private/var/db/PowerUI/mac_routine_eng.mlmodelc
/System/Volumes/Data/private/var/db/PowerUI/shallow_model.mlmodelc
/System/Volumes/Data/Users/josh/Code/whisper.cpp/models/ggml-large-v1-encoder.mlmodelc
/System/Volumes/Data/Users/josh/Code/Whisper/whisper.cpp/models/ggml-small-encoder.mlmodelc
/System/Volumes/Data/Users/josh/Code/Whisper/whisper.cpp/models/ggml-large-encoder.mlmodelc
/System/Volumes/Data/Users/josh/Code/Whisper/whisper.cpp/models/ggml-medium-encoder.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/lipsync.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/SuperResolution180pModel.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/hlm.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/SuperResolution270pModel.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/hd.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/afn_mac.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/flm.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/SuperResolution360pModel.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/afn_mac_premium.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/bgr_mac.mlmodelc
/System/Volumes/Data/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/bgr_mac_premium.mlmodelc
/System/Volumes/Data/Applications/UniChar.app/Wrapper/UniChar Picker.app/Symbols.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/Decontamination.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/MaskRefinement.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/ColorFixing.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/AutoCrop.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/NoiseAnalysis.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/ImageAnalysis.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/NoiseReduction.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/SuperResolution.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/LayerNaming.mlmodelc
/System/Volumes/Data/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/ObjectDetection.mlmodelc
/System/Volumes/Data/Applications/GarageBand.app/Contents/Frameworks/MAMusicAnalysis.framework/Versions/A/Resources/OnsetDetectionCNN.mlmodelc
/System/Volumes/Data/Applications/Draw Things.app/Contents/Resources/DeepLabV3FP16.mlmodelc
/System/Volumes/Data/Applications/Draw Things.app/Contents/Resources/mlsd_v1.mlmodelc
/private/var/db/PowerUI/mac_routine_reg.mlmodelc
/private/var/db/PowerUI/mac_routine_eng.mlmodelc
/private/var/db/PowerUI/shallow_model.mlmodelc
/Users/josh/Code/whisper.cpp/models/ggml-large-v1-encoder.mlmodelc
/Users/josh/Code/Whisper/whisper.cpp/models/ggml-small-encoder.mlmodelc
/Users/josh/Code/Whisper/whisper.cpp/models/ggml-large-encoder.mlmodelc
/Users/josh/Code/Whisper/whisper.cpp/models/ggml-medium-encoder.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/lipsync.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/SuperResolution180pModel.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/hlm.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/SuperResolution270pModel.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/hd.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/afn_mac.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/flm.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/SuperResolution360pModel.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/afn_mac_premium.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/bgr_mac.mlmodelc
/Applications/zoom.us.app/Contents/Frameworks/aomhost.app/Contents/Frameworks/libcmlFramework.framework/Versions/A/Resources/bgr_mac_premium.mlmodelc
/Applications/UniChar.app/Wrapper/UniChar Picker.app/Symbols.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/Decontamination.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/MaskRefinement.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/ColorFixing.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/AutoCrop.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/NoiseAnalysis.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/ImageAnalysis.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/NoiseReduction.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/SuperResolution.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/LayerNaming.mlmodelc
/Applications/Pixelmator Pro.app/Contents/Frameworks/PXMPro.framework/Versions/A/Resources/ObjectDetection.mlmodelc
/Applications/GarageBand.app/Contents/Frameworks/MAMusicAnalysis.framework/Versions/A/Resources/OnsetDetectionCNN.mlmodelc
/Applications/Draw Things.app/Contents/Resources/DeepLabV3FP16.mlmodelc
/Applications/Draw Things.app/Contents/Resources/mlsd_v1.mlmodelc

"""